# Generated by Django 4.1.7 on 2023-03-13 13:04

from django.db import migrations, models
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OhlcPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unix', django_unixdatetimefield.fields.UnixDateTimeField()),
                ('date', models.DateTimeField()),
                ('symbol', models.CharField(max_length=10)),
                ('open', models.DecimalField(decimal_places=8, max_digits=18, null=True)),
                ('high', models.DecimalField(decimal_places=8, max_digits=18, null=True)),
                ('low', models.DecimalField(decimal_places=8, max_digits=18, null=True)),
                ('close', models.DecimalField(decimal_places=8, max_digits=18, null=True)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('volume_base', models.DecimalField(decimal_places=8, max_digits=18, null=True)),
                ('interval', models.IntegerField()),
            ],
            options={
                'db_table': 'ohlc_price',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SymbolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('url_symbol', models.CharField(max_length=10)),
                ('base_decimals', models.IntegerField()),
                ('counter_decimals', models.IntegerField()),
                ('trading', models.CharField(max_length=8)),
                ('description', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'symbol_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TslaPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unix', django_unixdatetimefield.fields.UnixDateTimeField()),
                ('date', models.DateTimeField()),
                ('symbol', models.CharField(max_length=10)),
                ('open', models.DecimalField(decimal_places=8, max_digits=18, null=True)),
                ('high', models.DecimalField(decimal_places=8, max_digits=18, null=True)),
                ('low', models.DecimalField(decimal_places=8, max_digits=18, null=True)),
                ('close', models.DecimalField(decimal_places=8, max_digits=18, null=True)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('volume_base', models.DecimalField(decimal_places=8, max_digits=18, null=True)),
                ('interval', models.IntegerField()),
            ],
            options={
                'db_table': 'tsla_price',
                'managed': True,
            },
        ),
    ]
