# Generated by Django 4.1.7 on 2023-03-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ohlcprice',
            name='market_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='symbolinfo',
            name='market_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tslaprice',
            name='market_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
