# Generated by Django 4.1.7 on 2023-03-23 21:19

from django.db import migrations, models
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ohlcprice_market_id_symbolinfo_market_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unix', django_unixdatetimefield.fields.UnixDateTimeField()),
                ('symbol', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=18)),
                ('tid', models.CharField(max_length=10)),
                ('trade_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unix', django_unixdatetimefield.fields.UnixDateTimeField()),
                ('timestamp', models.DateTimeField()),
                ('symbol', models.CharField(max_length=10)),
                ('interval', models.CharField(max_length=10)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('ma_20', models.DecimalField(decimal_places=8, max_digits=18)),
                ('ma_50', models.DecimalField(decimal_places=8, max_digits=18)),
                ('macd', models.DecimalField(decimal_places=8, max_digits=18)),
                ('signal_line', models.DecimalField(decimal_places=8, max_digits=18)),
                ('histogram', models.DecimalField(decimal_places=8, max_digits=18)),
                ('upper_macd', models.DecimalField(decimal_places=8, max_digits=18)),
                ('lower_macd', models.DecimalField(decimal_places=8, max_digits=18)),
                ('rsi', models.DecimalField(decimal_places=8, max_digits=18)),
                ('kdj_k', models.DecimalField(decimal_places=8, max_digits=18)),
                ('kdj_d', models.DecimalField(decimal_places=8, max_digits=18)),
                ('kdj_j', models.DecimalField(decimal_places=8, max_digits=18)),
                ('stochastic_oscillator_k', models.DecimalField(decimal_places=8, max_digits=18)),
                ('stochastic_oscillator_d', models.DecimalField(decimal_places=8, max_digits=18)),
            ],
            options={
                'unique_together': {('symbol', 'interval', 'unix')},
            },
        ),
    ]
