# Generated by Django 4.1.7 on 2023-03-23 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tradedata_indicator'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='indicator',
            table='qt_indicator',
        ),
        migrations.AlterModelTable(
            name='ohlcprice',
            table='qt_ohlc',
        ),
        migrations.AlterModelTable(
            name='symbolinfo',
            table='qt_symbol_info',
        ),
        migrations.AlterModelTable(
            name='tradedata',
            table='qt_tradedata',
        ),
        migrations.AlterModelTable(
            name='tslaprice',
            table='qt_tsla',
        ),
    ]
