# Generated by Django 4.1.7 on 2023-03-24 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_alter_indicator_table_alter_ohlcprice_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OhlcPriceMinute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unix', django_unixdatetimefield.fields.UnixDateTimeField()),
                ('date', models.DateTimeField()),
                ('symbol', models.CharField(max_length=10)),
                ('open', models.DecimalField(decimal_places=8, max_digits=18, null=True)),
                ('high', models.DecimalField(decimal_places=8, max_digits=18, null=True)),
                ('low', models.DecimalField(decimal_places=8, max_digits=18, null=True)),
                ('close', models.DecimalField(decimal_places=8, max_digits=18, null=True)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('volume_base', models.DecimalField(decimal_places=8, max_digits=18, null=True)),
                ('market_id', models.IntegerField()),
                ('interval', models.IntegerField()),
            ],
            options={
                'db_table': 'qt_ohlc_m',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_user_id', models.CharField(max_length=30)),
                ('market_id', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tu_user',
            },
        ),
        migrations.CreateModel(
            name='UserTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=18)),
                ('unix', django_unixdatetimefield.fields.UnixDateTimeField()),
                ('timestamp', models.DateTimeField()),
                ('market_id', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
            options={
                'db_table': 'tu_trade',
            },
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('order_type', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=18)),
                ('status', models.CharField(max_length=10)),
                ('market_id', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
            options={
                'db_table': 'tu_order',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('transaction_type', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('market_id', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
            options={
                'db_table': 'tu_transaction',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=18)),
                ('average_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('balance', models.DecimalField(decimal_places=8, max_digits=18)),
                ('market_id', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
            options={
                'db_table': 'tu_portfolio',
            },
        ),
    ]
