# Generated by Django 4.1.7 on 2023-03-30 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_indicatorminute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicator',
            old_name='lower_macd',
            new_name='lower_ema',
        ),
        migrations.RenameField(
            model_name='indicator',
            old_name='upper_macd',
            new_name='upper_ema',
        ),
        migrations.RenameField(
            model_name='indicatorminute',
            old_name='lower_macd',
            new_name='lower_ema',
        ),
        migrations.RenameField(
            model_name='indicatorminute',
            old_name='upper_macd',
            new_name='upper_ema',
        ),
    ]
