# Generated by Django 4.1.7 on 2023-03-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_lower_macd_indicator_lower_ema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='ema',
            field=models.DecimalField(decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='indicatorminute',
            name='ema',
            field=models.DecimalField(decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='histogram',
            field=models.DecimalField(decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='kdj_d',
            field=models.DecimalField(decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='kdj_j',
            field=models.DecimalField(decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='kdj_k',
            field=models.DecimalField(decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='lower_ema',
            field=models.DecimalField(decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='ma_20',
            field=models.DecimalField(decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='ma_50',
            field=models.DecimalField(decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='macd',
            field=models.DecimalField(decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='rsi',
            field=models.DecimalField(decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='signal_line',
            field=models.DecimalField(decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='stochastic_oscillator_d',
            field=models.DecimalField(decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='stochastic_oscillator_k',
            field=models.DecimalField(decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='upper_ema',
            field=models.DecimalField(decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='indicatorminute',
            name='histogram',
            field=models.DecimalField(decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='indicatorminute',
            name='kdj_d',
            field=models.DecimalField(decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='indicatorminute',
            name='kdj_j',
            field=models.DecimalField(decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='indicatorminute',
            name='kdj_k',
            field=models.DecimalField(decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='indicatorminute',
            name='lower_ema',
            field=models.DecimalField(decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='indicatorminute',
            name='ma_20',
            field=models.DecimalField(decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='indicatorminute',
            name='ma_50',
            field=models.DecimalField(decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='indicatorminute',
            name='macd',
            field=models.DecimalField(decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='indicatorminute',
            name='rsi',
            field=models.DecimalField(decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='indicatorminute',
            name='signal_line',
            field=models.DecimalField(decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='indicatorminute',
            name='stochastic_oscillator_d',
            field=models.DecimalField(decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='indicatorminute',
            name='stochastic_oscillator_k',
            field=models.DecimalField(decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='indicatorminute',
            name='upper_ema',
            field=models.DecimalField(decimal_places=8, max_digits=18, null=True),
        ),
    ]
