# Generated by Django 4.1.7 on 2023-03-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_indicator_ema_indicatorminute_ema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='interval',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='indicatorminute',
            name='interval',
            field=models.IntegerField(),
        ),
    ]
