# Generated by Django 4.1.7 on 2023-04-06 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_indicator_interval_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicator',
            old_name='stochastic_oscillator_d',
            new_name='stoch_d',
        ),
        migrations.RenameField(
            model_name='indicator',
            old_name='stochastic_oscillator_k',
            new_name='stoch_k',
        ),
        migrations.RenameField(
            model_name='indicatorminute',
            old_name='stochastic_oscillator_d',
            new_name='stoch_d',
        ),
        migrations.RenameField(
            model_name='indicatorminute',
            old_name='stochastic_oscillator_k',
            new_name='stoch_k',
        ),
    ]
