# Generated by Django 5.2.7 on 2025-10-09 05:59

import django_unixdatetimefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_stochastic_oscillator_d_indicator_stoch_d_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='adx',
            field=models.DecimalField(decimal_places=8, max_digits=18, null=True),
        ),
        migrations.CreateModel(
            name='MarketRegime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unix', django_unixdatetimefield.fields.UnixDateTimeField()),
                ('timestamp', models.DateTimeField()),
                ('symbol', models.CharField(max_length=10)),
                ('interval', models.IntegerField()),
                ('regime_type', models.CharField(max_length=20)),
                ('trend_direction', models.CharField(max_length=10, null=True)),
                ('adx', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('channel_in_pct', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('channel_width_pct', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('higher_tf_trend', models.CharField(max_length=10, null=True)),
                ('volume_ratio', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'qt_market_regime',
                'indexes': [models.Index(fields=['symbol', 'interval', 'timestamp'], name='qt_market_r_symbol_72c0db_idx')],
                'unique_together': {('symbol', 'interval', 'unix')},
            },
        ),
        migrations.CreateModel(
            name='TradingSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unix', django_unixdatetimefield.fields.UnixDateTimeField()),
                ('timestamp', models.DateTimeField()),
                ('symbol', models.CharField(max_length=10)),
                ('interval', models.IntegerField()),
                ('signal_type', models.CharField(max_length=10)),
                ('strategy', models.CharField(max_length=30)),
                ('market_regime', models.CharField(max_length=20)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('stop_loss', models.DecimalField(decimal_places=8, max_digits=18, null=True)),
                ('take_profit', models.DecimalField(decimal_places=8, max_digits=18, null=True)),
                ('risk_pct', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('reward_pct', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('trigger_reason', models.TextField()),
                ('rsi_value', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('macd_value', models.DecimalField(decimal_places=8, max_digits=18, null=True)),
                ('volume_ratio', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('exit_price', models.DecimalField(decimal_places=8, max_digits=18, null=True)),
                ('exit_timestamp', models.DateTimeField(null=True)),
                ('pnl_pct', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'qt_trading_signal',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', 'interval', 'timestamp'], name='qt_trading__symbol_62dcf5_idx'), models.Index(fields=['status', 'signal_type'], name='qt_trading__status_090995_idx'), models.Index(fields=['created_at'], name='qt_trading__created_517d93_idx')],
            },
        ),
    ]

